#Makefile
CC = gcc
INCLUDE = /usr/lib
LIBS = 
OBJS = 
HEADERS= .
all: clientExample 

clientExample: 
	$(CC)  -o clientExample util.c clientExample.c  -I$(HEADERS) $(CFLAGS) $(LIBS)

clean:
	rm -f clientExample  

