#Makefile
CC = gcc
INCLUDE = /usr/lib
LIBS = 
OBJS = 
HEADERS= .
all:  serverExample

serverExample:
	$(CC) -o serverExample util.c serverExample.c -I$(HEADERS) $(CFLAGS) $(LIBS)

clean:
	rm -f  serverExample 

